[project]
name = "tiendo"
version = "0.1.0"
description = "Basic international virtual store"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.121.3",
    "jinja2>=3.1.6",
    "pywebview>=6.1",
    "requests>=2.32.5",
    "uvicorn>=0.38.0",
]
